// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mcplantainer

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5bd79fa1DecodeMevericcoreMcplantainer(in *jlexer.Lexer, out *ShadowUpdateRPCMsgSt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "args":
			easyjson5bd79fa1DecodeMevericcoreMcplantainer1(in, &out.Args)
		case "src":
			out.Src = string(in.String())
		case "dst":
			out.Dst = string(in.String())
		case "method":
			out.Method = string(in.String())
		case "id":
			out.Id = int(in.Int())
		case "error":
			if in.IsNull() {
				in.Skip()
				out.Error = nil
			} else {
				if out.Error == nil {
					out.Error = new(map[string]interface{})
				}
				if in.IsNull() {
					in.Skip()
				} else {
					in.Delim('{')
					if !in.IsDelim('}') {
						*out.Error = make(map[string]interface{})
					} else {
						*out.Error = nil
					}
					for !in.IsDelim('}') {
						key := string(in.String())
						in.WantColon()
						var v1 interface{}
						if m, ok := v1.(easyjson.Unmarshaler); ok {
							m.UnmarshalEasyJSON(in)
						} else if m, ok := v1.(json.Unmarshaler); ok {
							_ = m.UnmarshalJSON(in.Raw())
						} else {
							v1 = in.Interface()
						}
						(*out.Error)[key] = v1
						in.WantComma()
					}
					in.Delim('}')
				}
			}
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				if out.Result == nil {
					out.Result = new(map[string]interface{})
				}
				if in.IsNull() {
					in.Skip()
				} else {
					in.Delim('{')
					if !in.IsDelim('}') {
						*out.Result = make(map[string]interface{})
					} else {
						*out.Result = nil
					}
					for !in.IsDelim('}') {
						key := string(in.String())
						in.WantColon()
						var v2 interface{}
						if m, ok := v2.(easyjson.Unmarshaler); ok {
							m.UnmarshalEasyJSON(in)
						} else if m, ok := v2.(json.Unmarshaler); ok {
							_ = m.UnmarshalJSON(in.Raw())
						} else {
							v2 = in.Interface()
						}
						(*out.Result)[key] = v2
						in.WantComma()
					}
					in.Delim('}')
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5bd79fa1EncodeMevericcoreMcplantainer(out *jwriter.Writer, in ShadowUpdateRPCMsgSt) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"args\":")
		easyjson5bd79fa1EncodeMevericcoreMcplantainer1(out, in.Args)
	}
	if in.Src != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"src\":")
		out.String(string(in.Src))
	}
	if in.Dst != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"dst\":")
		out.String(string(in.Dst))
	}
	if in.Method != "" {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"method\":")
		out.String(string(in.Method))
	}
	if in.Id != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"id\":")
		out.Int(int(in.Id))
	}
	if in.Error != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"error\":")
		if in.Error == nil {
			out.RawString("null")
		} else {
			if *in.Error == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
				out.RawString(`null`)
			} else {
				out.RawByte('{')
				v3First := true
				for v3Name, v3Value := range *in.Error {
					if !v3First {
						out.RawByte(',')
					}
					v3First = false
					out.String(string(v3Name))
					out.RawByte(':')
					if m, ok := v3Value.(easyjson.Marshaler); ok {
						m.MarshalEasyJSON(out)
					} else if m, ok := v3Value.(json.Marshaler); ok {
						out.Raw(m.MarshalJSON())
					} else {
						out.Raw(json.Marshal(v3Value))
					}
				}
				out.RawByte('}')
			}
		}
	}
	if in.Result != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"result\":")
		if in.Result == nil {
			out.RawString("null")
		} else {
			if *in.Result == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
				out.RawString(`null`)
			} else {
				out.RawByte('{')
				v4First := true
				for v4Name, v4Value := range *in.Result {
					if !v4First {
						out.RawByte(',')
					}
					v4First = false
					out.String(string(v4Name))
					out.RawByte(':')
					if m, ok := v4Value.(easyjson.Marshaler); ok {
						m.MarshalEasyJSON(out)
					} else if m, ok := v4Value.(json.Marshaler); ok {
						out.Raw(m.MarshalJSON())
					} else {
						out.Raw(json.Marshal(v4Value))
					}
				}
				out.RawByte('}')
			}
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShadowUpdateRPCMsgSt) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5bd79fa1EncodeMevericcoreMcplantainer(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShadowUpdateRPCMsgSt) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5bd79fa1EncodeMevericcoreMcplantainer(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShadowUpdateRPCMsgSt) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5bd79fa1DecodeMevericcoreMcplantainer(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShadowUpdateRPCMsgSt) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5bd79fa1DecodeMevericcoreMcplantainer(l, v)
}
func easyjson5bd79fa1DecodeMevericcoreMcplantainer1(in *jlexer.Lexer, out *PlantainerShadowRPCMsgArgsSt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "state":
			easyjson5bd79fa1DecodeMevericcoreMcplantainer2(in, &out.State)
		case "version":
			out.Version = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5bd79fa1EncodeMevericcoreMcplantainer1(out *jwriter.Writer, in PlantainerShadowRPCMsgArgsSt) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"state\":")
		easyjson5bd79fa1EncodeMevericcoreMcplantainer2(out, in.State)
	}
	if in.Version != 0 {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"version\":")
		out.Int(int(in.Version))
	}
	out.RawByte('}')
}
func easyjson5bd79fa1DecodeMevericcoreMcplantainer2(in *jlexer.Lexer, out *PlantainerShadowRPCMsgArgsStateSt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "reported":
			if in.IsNull() {
				in.Skip()
				out.Reported = nil
			} else {
				if out.Reported == nil {
					out.Reported = new(PlantainerShadowStatePieceSt)
				}
				(*out.Reported).UnmarshalEasyJSON(in)
			}
		case "desired":
			if in.IsNull() {
				in.Skip()
				out.Desired = nil
			} else {
				if out.Desired == nil {
					out.Desired = new(PlantainerShadowStatePieceSt)
				}
				(*out.Desired).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5bd79fa1EncodeMevericcoreMcplantainer2(out *jwriter.Writer, in PlantainerShadowRPCMsgArgsStateSt) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Reported != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"reported\":")
		if in.Reported == nil {
			out.RawString("null")
		} else {
			(*in.Reported).MarshalEasyJSON(out)
		}
	}
	if in.Desired != nil {
		if !first {
			out.RawByte(',')
		}
		first = false
		out.RawString("\"desired\":")
		if in.Desired == nil {
			out.RawString("null")
		} else {
			(*in.Desired).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}
